version: '3.9'

services:
  skrambllanding:
    container_name: 'skrambl-landing'
    build: .
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - '3000:3000'
